name=ESP32_Lua
version=0.8.9
author=Evgeniy Fedorenko
maintainer=Evgeniy Fedorenko
sentence=Lua interpreter for ESP32 with display and input support.
paragraph=This library embeds Lua interpreter for ESP32, adds TFT display, touch, and GPIO support.
category=Other
url=https://github.com/PerrotSoft/ESP32_Lua
architectures=esp32
